"""
This type stub file was generated by pyright.
"""

import datetime

NTP_EPOCH = ...
def current_datetime() -> datetime.datetime:
    ...

def current_ms() -> int:
    ...

def current_ntp_time() -> int:
    ...

def datetime_from_ntp(ntp: int) -> datetime.datetime:
    ...

def datetime_to_ntp(dt: datetime.datetime) -> int:
    ...

