"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from .mediastreams import MediaStreamTrack
from .rtcrtpreceiver import RTCRtpReceiver
from .rtcrtptransceiver import RTCRtpTransceiver

@dataclass
class RTCTrackEvent:
    """
    This event is fired on :class:`RTCPeerConnection` when a new
    :class:`MediaStreamTrack` is added by the remote party.
    """
    receiver: RTCRtpReceiver
    track: MediaStreamTrack
    transceiver: RTCRtpTransceiver
    ...


