"""
This type stub file was generated by pyright.
"""

class InternalError(Exception):
    ...


class InvalidAccessError(Exception):
    ...


class InvalidStateError(Exception):
    ...


class OperationError(Exception):
    ...


