"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple
from .rtp import RtpPacket

MAX_MISORDER = ...
class JitterFrame:
    def __init__(self, data: bytes, timestamp: int) -> None:
        ...
    


class JitterBuffer:
    def __init__(self, capacity: int, prefetch: int = ..., is_video: bool = ...) -> None:
        ...
    
    @property
    def capacity(self) -> int:
        ...
    
    def add(self, packet: RtpPacket) -> Tuple[bool, Optional[JitterFrame]]:
        ...
    
    def remove(self, count: int) -> None:
        ...
    
    def smart_remove(self, count: int) -> bool:
        """
        Makes sure that all packages belonging to the same frame are removed
        to prevent sending corrupted frames to the decoder.
        """
        ...
    


