"""
This type stub file was generated by pyright.
"""

def random16() -> int:
    ...

def random32() -> int:
    ...

def uint16_add(a: int, b: int) -> int:
    """
    Return a + b.
    """
    ...

def uint16_gt(a: int, b: int) -> bool:
    """
    Return a > b.
    """
    ...

def uint16_gte(a: int, b: int) -> bool:
    """
    Return a >= b.
    """
    ...

def uint32_add(a: int, b: int) -> int:
    """
    Return a + b.
    """
    ...

def uint32_gt(a: int, b: int) -> bool:
    """
    Return a > b.
    """
    ...

def uint32_gte(a: int, b: int) -> bool:
    """
    Return a >= b.
    """
    ...

