"""
This type stub file was generated by pyright.
"""

from abc import ABCMeta, abstractmethod
from typing import List, Tuple
from av.frame import Frame
from av.packet import Packet
from ..jitterbuffer import JitterFrame

class Decoder(metaclass=ABCMeta):
    @abstractmethod
    def decode(self, encoded_frame: JitterFrame) -> List[Frame]:
        ...
    


class Encoder(metaclass=ABCMeta):
    @abstractmethod
    def encode(self, frame: Frame, force_keyframe: bool = ...) -> Tuple[List[bytes], int]:
        ...
    
    @abstractmethod
    def pack(self, packet: Packet) -> Tuple[List[bytes], int]:
        ...
    


