"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple
from av.frame import Frame
from av.packet import Packet
from ..jitterbuffer import JitterFrame
from .base import Decoder, Encoder

SAMPLE_RATE = ...
SAMPLE_WIDTH = ...
SAMPLES_PER_FRAME = ...
TIME_BASE = ...
class PcmDecoder(Decoder):
    def __init__(self, codec_name: str) -> None:
        ...
    
    def decode(self, encoded_frame: JitterFrame) -> List[Frame]:
        ...
    


class PcmEncoder(Encoder):
    def __init__(self, codec_name: str) -> None:
        ...
    
    def encode(self, frame: Frame, force_keyframe: bool = ...) -> Tuple[List[bytes], int]:
        ...
    
    def pack(self, packet: Packet) -> Tuple[List[bytes], int]:
        ...
    


class PcmaDecoder(PcmDecoder):
    def __init__(self) -> None:
        ...
    


class PcmaEncoder(PcmEncoder):
    def __init__(self) -> None:
        ...
    


class PcmuDecoder(PcmDecoder):
    def __init__(self) -> None:
        ...
    


class PcmuEncoder(PcmEncoder):
    def __init__(self) -> None:
        ...
    


